#!/usr/bin/sh
basedir=$(realpath $(dirname "$0"))
mkdir "$basedir"/output
find "$basedir"/output -mindepth 1 -type f -delete
cp -v "$basedir"/../static/index.css "$basedir"/output/
cp -v "$basedir"/../static/extrastyle.css "$basedir"/output/
find "$basedir" -name '*.md' | while read line
do
	shortname=$(basename "$line")
	pandoc -f markdown+rebase_relative_paths -t html \
		--toc --shift-heading-level-by=-1 \
		-B "$basedir"/header.html \
		-V toc-title:"Table of Contents" \
		-s -c "$basedir"/output/index.css -c "$basedir"/output/extrastyle.css \
		"$line" \
		-o "$basedir"/output/$(echo "$shortname" | sed -e "s/md\$/html/")
done
mv -v "$basedir"/output/* "$basedir"/../dist/writeups
find "$basedir"/../dist/writeups -name '*.html' -exec sed -e 's/href=".*output\//href="/' -i {} \;
